package com.example.bibliotecadb

class InitBooks {

    suspend fun AddBooks(bookDao: BookDao) {
        println("Writting Books Beggin")
        bookDao.addBook(Book("Gabriel García Márquez", "Cien años de soledad", 471, "Una saga familiar que narra la historia de Macondo a través de siete generaciones de la familia Buendía.", R.drawable.book_black))
        bookDao.addBook(Book("Gabriel García Márquez", "El amor en los tiempos del cólera", 368, "La historia de amor entre Fermina Daza y Florentino Ariza, que se extiende a lo largo de más de 50 años.", R.drawable.book_blue))
        bookDao.addBook(Book("Gabriel García Márquez", "El coronel no tiene quien le escriba", 112, "La historia de un coronel retirado que espera una carta que le confirme la pensión que le adeuda el gobierno.", R.drawable.book_green))
        bookDao.addBook(Book("Gabriel García Márquez", "La casa de los espíritus", 487, "Una saga familiar que narra la historia de la familia Trueba a lo largo de varias generaciones.", R.drawable.book_red))
        bookDao.addBook(Book("Gabriel García Márquez", "Crónica de una muerte anunciada", 256, "La historia del asesinato de Santiago Nasar, anunciado a viva voz por sus propios verdugos.", R.drawable.book_white))
        bookDao.addBook(Book("Mario Vargas Llosa", "La ciudad y los perros", 444, "La historia de un grupo de cadetes en un colegio militar en Lima, Perú.", R.drawable.book_yellow))
        bookDao.addBook(Book("Mario Vargas Llosa", "La casa verde", 584, "Un relato complejo que se desarrolla en la Amazonía peruana y explora temas como la violencia, la explotación y la corrupción.", R.drawable.book_black))
        bookDao.addBook(Book("Mario Vargas Llosa", "Conversación en la Catedral", 768, "Una novela policiaca que explora la violencia política en el Perú.", R.drawable.book_blue))
        bookDao.addBook(Book("Mario Vargas Llosa", "La tía Julia y el escribidor", 312, "Una novela autobiográfica que narra la historia del joven Mario Vargas Llosa y su relación con su tía Julia.", R.drawable.book_green))
        bookDao.addBook(Book("Mario Vargas Llosa", "La fiesta del Chivo", 512, "Una novela histórica que narra la vida del dictador dominicano Rafael Trujillo.", R.drawable.book_red))
        bookDao.addBook(Book("Mario Vargas Llosa", "Los cachorros", 240, "Un conjunto de cuentos que narran la vida de un grupo de jóvenes en Lima, Perú.", R.drawable.book_white))
        bookDao.addBook(Book("Mario Vargas Llosa", "Elogio de la madrastra", 304, "Una novela que explora las relaciones familiares y la sexualidad.", R.drawable.book_yellow))
        bookDao.addBook(Book("Mario Vargas Llosa", "La guerra del fin del mundo", 672, "Una novela histórica que narra la Guerra de Canudos en Brasil a finales del siglo XIX.", R.drawable.book_black))
        bookDao.addBook(Book("Mario Vargas Llosa", "El sueño del celta", 496, "Una novela que narra la historia de Roger Casement, un diplomático británico que luchó por los derechos de los indígenas en el Congo Belga.", R.drawable.book_blue))
        bookDao.addBook(Book("Mario Vargas Llosa", "El paraíso en la otra esquina", 544, "Una novela que narra la historia de Paul Gauguin y su viaje a Tahití.", R.drawable.book_green))
        bookDao.addBook(Book("Jorge Luis Borges", "Ficciones", 256, "Un conjunto de cuentos que exploran temas como el tiempo, el laberinto, la identidad y la realidad.", R.drawable.book_red))
        bookDao.addBook(Book("Jorge Luis Borges", "El Aleph", 224, "Un conjunto de relatos que exploran temas como la metafísica, la literatura y la religión.", R.drawable.book_white))
        bookDao.addBook(Book("Jorge Luis Borges", "El Hacedor", 208, "Un conjunto de poemas que exploran temas como el tiempo, la muerte y la memoria.", R.drawable.book_yellow))
        bookDao.addBook(Book("Jorge Luis Borges", "Otras inquisiciones", 240, "Un conjunto de ensayos que exploran temas como la literatura, la filosofía y la historia.", R.drawable.book_black))
        bookDao.addBook(Book("Jorge Luis Borges", "La muerte y la brújula", 192, "Un conjunto de cuentos que exploran temas como el detective, la muerte y el destino.", R.drawable.book_blue))
        bookDao.addBook(Book("Jorge Luis Borges", "Historia de la eternidad", 160, "Un conjunto de ensayos que exploran temas como el tiempo, la eternidad y el infinito.", R.drawable.book_green))
        bookDao.addBook(Book("Jorge Luis Borges", "Siete noches", 128, "Un conjunto de conferencias que exploran temas como la literatura, la filosofía y la religión.", R.drawable.book_red))
        bookDao.addBook(Book("Jorge Luis Borges", "El libro de arena", 128, "Un conjunto de cuentos que exploran temas como el tiempo, la memoria y la realidad.", R.drawable.book_white))
        bookDao.addBook(Book("Jorge Luis Borges", "Atlas", 112, "Un conjunto de poemas que exploran temas como la geografía, la historia y la memoria.", R.drawable.book_yellow))
        bookDao.addBook(Book("Jorge Luis Borges", "El oro de los tigres", 112, "Un conjunto de cuentos que exploran temas como los sueños, la memoria y la muerte.", R.drawable.book_black))
        bookDao.addBook(Book("Julio Cortázar", "Rayuela", 560, "Una novela experimental que explora temas como el tiempo, el espacio y la libertad.", R.drawable.book_blue))
        bookDao.addBook(Book("Julio Cortázar", "Historias de cronopios y de famas", 192, "Un conjunto de cuentos que exploran temas como lo fantástico, lo cotidiano y el humor.", R.drawable.book_green))
        bookDao.addBook(Book("Julio Cortázar", "Final del juego", 224, "Una novela que explora temas como la incomunicación, la soledad y el absurdo.", R.drawable.book_red))
        bookDao.addBook(Book("Julio Cortázar", "Los premios", 384, "Una novela que explora temas como la alienación, la burocracia y la deshumanización.", R.drawable.book_white))
        bookDao.addBook(Book("Julio Cortázar", "Libro de Manuel", 176, "Una novela experimental que explora temas como la política, la revolución y la violencia.", R.drawable.book_yellow))
        bookDao.addBook(Book("Julio Cortázar", "Octaedro", 208, "Un conjunto de cuentos que exploran temas como lo fantástico, lo cotidiano y el humor.", R.drawable.book_black))
        bookDao.addBook(Book("Julio Cortázar", "Todos los fuegos el fuego", 224, "Un conjunto de cuentos que exploran temas como el amor, la muerte y la soledad.", R.drawable.book_blue))
        bookDao.addBook(Book("Julio Cortázar", "La vuelta al día en ochenta mundos", 352, "Una novela que explora temas como la literatura, la traducción y la imaginación.", R.drawable.book_green))
        bookDao.addBook(Book("Julio Cortázar", "El perseguidor", 208, "Una novela que explora temas como el jazz, la música y la búsqueda del yo.", R.drawable.book_red))
        bookDao.addBook(Book("Julio Cortázar", "Prosa del observatorio", 224, "Un conjunto de textos que exploran temas como la política, la sociedad y la cultura.", R.drawable.book_white))
        bookDao.addBook(Book("Isabel Allende", "De amor y de sombra", 320, "Una novela que explora temas como el amor, la política y la violencia.", R.drawable.book_yellow))
        bookDao.addBook(Book("Isabel Allende", "Eva Luna", 352, "Una novela que explora temas como la identidad, la búsqueda del yo y la libertad.", R.drawable.book_black))
        bookDao.addBook(Book("Isabel Allende", "El plan infinito", 304, "Una novela que explora temas como el amor, la muerte y la familia.", R.drawable.book_blue))
        bookDao.addBook(Book("Isabel Allende", "El juego de Ripper", 400, "Una novela que explora temas como la violencia, la venganza y la redención.", R.drawable.book_green))
        bookDao.addBook(Book("Isabel Allende", "Inés del alma mía", 496, "Una novela histórica que narra la vida de Inés Suárez, una de las primeras mujeres que llegó a Chile en el siglo XVI.", R.drawable.book_red))
        bookDao.addBook(Book("Isabel Allende", "El amante japonés", 320, "Una novela que explora temas como el amor, la pérdida y la memoria.", R.drawable.book_white))
        bookDao.addBook(Book("Isabel Allende", "La suma de los días", 544, "Una novela que explora temas como la familia, la amistad y el amor.", R.drawable.book_yellow))
        bookDao.addBook(Book("Isabel Allende", "Largo pétalo de mar", 576, "Una novela que explora temas como el exilio, la guerra civil española y la búsqueda del yo.", R.drawable.book_black))
        bookDao.addBook(Book("Isabel Allende", " Mujeres del alma mía", 336, "Un conjunto de historias que exploran las vidas de mujeres de diferentes culturas y épocas.", R.drawable.book_blue))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "La sombra del viento", 496, "Una novela que explora temas como la literatura, el misterio y la amistad.", R.drawable.book_green))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "El juego del ángel", 544, "Una novela que explora temas como la literatura, la religión y la muerte.", R.drawable.book_red))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "El prisionero del cielo", 528, "Una novela que explora temas como la literatura, la amistad y el amor.", R.drawable.book_white))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "El laberinto de los espíritus", 608, "Una novela que explora temas como la literatura, la familia y la memoria.", R.drawable.book_yellow))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "Marina", 336, "Una novela que explora temas como el amor, la pérdida y la memoria.", R.drawable.book_black))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "El príncipe de la niebla", 512, "Una novela que explora temas como el misterio, la amistad y la aventura.", R.drawable.book_blue))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "Las luces de septiembre", 448, "Una novela que explora temas como la literatura, la amistad y el amor.", R.drawable.book_green))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "El fuego invisible", 560, "Una novela que explora temas como la literatura, la amistad y el amor.", R.drawable.book_red))
        bookDao.addBook(Book("Carlos Ruiz Zafón", "La ciudad de las estrellas fugaces", 544, "Una novela que explora temas como la literatura, la amistad y el amor.", R.drawable.book_white))
        bookDao.addBook(Book("Laura Restrepo", "Leopardo al sol", 320, "Una novela que explora temas como la violencia, la política y la corrupción.", R.drawable.book_yellow))
        bookDao.addBook(Book("Laura Restrepo", "La isla de la pasión", 384, "Una novela que explora temas como el amor, la aventura y la libertad.", R.drawable.book_black))
        bookDao.addBook(Book("Laura Restrepo", "Delirio", 272, "Una novela que explora temas como la memoria, la locura y la violencia.", R.drawable.book_blue))
        bookDao.addBook(Book("Laura Restrepo", "El ángel de la guarda", 352, "Una novela que explora temas como la violencia, la política y la corrupción.", R.drawable.book_green))
        bookDao.addBook(Book("Laura Restrepo", "La muerte de Elvis Presley", 240, "Un conjunto de cuentos que exploran temas como la violencia, la muerte y la soledad.", R.drawable.book_red))
        bookDao.addBook(Book("Laura Restrepo", "Los Divinos", 416, "Una novela que explora temas como la religión, la política y la corrupción.", R.drawable.book_white))
        bookDao.addBook(Book("Laura Restrepo", "Ojos de perro azul", 304, "Una novela que explora temas como la violencia, la política y la corrupción.", R.drawable.book_yellow))
        bookDao.addBook(Book("Laura Restrepo", "Hemingway en La Habana", 272, "Una novela que explora temas como la literatura, la amistad y la aventura.", R.drawable.book_black))
        bookDao.addBook(Book("Gioconda Belli", "La perra", 224, "Una novela que explora temas como la sexualidad, la política y la libertad.", R.drawable.book_blue))
        bookDao.addBook(Book("Gioconda Belli", "El país bajo mi piel", 208, "Una novela que explora temas como la identidad, la búsqueda del yo y la libertad.", R.drawable.book_green))
        bookDao.addBook(Book("Gioconda Belli", "Sofía de los presagios", 336, "Una novela que explora temas como la política, la guerra y la esperanza.", R.drawable.book_red))
        bookDao.addBook(Book("Gioconda Belli", "Waslala", 352, "Una novela que explora temas como la revolución, la guerra y la esperanza.", R.drawable.book_white))
        bookDao.addBook(Book("Gioconda Belli", "El infinito en la palma de la mano", 272, "Un conjunto de poemas que exploran temas como el amor, la vida y la muerte.", R.drawable.book_yellow))
        bookDao.addBook(Book("Gioconda Belli", "Lunas de Saturno", 240, "Un conjunto de poemas que exploran temas como el amor, la pérdida y la memoria.", R.drawable.book_black))
        bookDao.addBook(Book("José Saramago", "Ensayo sobre la ceguera", 320, "Una novela que explora temas como la ceguera, la sociedad y la condición humana.", R.drawable.book_blue))
        bookDao.addBook(Book("José Saramago", "Ensayo sobre la lucidez", 304, "Una novela que explora temas como la democracia, la participación ciudadana y la manipulación.", R.drawable.book_green))
        bookDao.addBook(Book("José Saramago", "La historia del cerco de Lisboa", 352, "Una novela que explora temas como el poder, la religión y la libertad.", R.drawable.book_red))
        bookDao.addBook(Book("José Saramago", "El Evangelio según Jesucristo", 384, "Una novela que explora temas como la religión, la fe y la justicia.", R.drawable.book_white))
        bookDao.addBook(Book("José Saramago", "Caín", 336, "Una novela que explora temas como la religión, la violencia y la libertad.", R.drawable.book_yellow))
        bookDao.addBook(Book("José Saramago", "El hombre duplicado", 320, "Una novela que explora temas como la identidad, la búsqueda del yo y la libertad.", R.drawable.book_black))
        bookDao.addBook(Book("Antonio Lobo Antunes", "Memoria de elefante", 368, "Una novela que explora temas como la guerra colonial portuguesa, la memoria y la culpa.", R.drawable.book_blue))
        bookDao.addBook(Book("Antonio Lobo Antunes", "Las explicaciones no son necesarias", 272, "Una novela que explora temas como la guerra colonial portuguesa, la memoria y la culpa.", R.drawable.book_green))
        bookDao.addBook(Book("Antonio Lobo Antunes", "Yo te prometo", 320, "Una novela que explora temas como el amor, la pérdida y la memoria.", R.drawable.book_red))
        bookDao.addBook(Book("Antonio Lobo Antunes", "El archipiélago de la nostalgia", 384, "Una novela que explora temas como la guerra colonial portuguesa, la memoria y la culpa.", R.drawable.book_white))
        bookDao.addBook(Book("Antonio Lobo Antunes", "Fábula", 240, "Una novela que explora temas como la guerra colonial portuguesa, la memoria y la culpa.", R.drawable.book_yellow))
        println("Writting Books Finished")
    }

}